package io.github.digitalsmile.goldberry.widgets;

/// Every widget one module contributes to markup.
///
/// The unit of §9's "built-ins and application widgets register identically". A
/// module that ships widgets provides one of these; an application that inflates
/// a document gets all of them, from every module on the path, without naming any
/// ([ADR-0131](../../../../../../book/src/adr/0131-a-widget-package-announces-itself.md)).
///
/// ## Nobody writes one
///
/// The implementation is **generated by the build** from the [Markup]
/// annotations in the module, and declared as a service by patching the module's
/// own `module-info`. A widget author annotates a class; a module author does
/// nothing at all.
///
/// It is an interface rather than a generated `Map` so that a module which needs
/// to register something conditionally — a widget behind a feature flag, a
/// platform-specific control — can hand-write one instead. That is the escape
/// hatch, not the road.
///
/// ## Found by `ServiceLoader`
///
/// Which resolves at **image build time** under GraalVM, so this is discovery
/// without a runtime scan: the closed world already knows every provider on the
/// module path (ADR-0127).
@FunctionalInterface
public interface WidgetCatalog {

    /// Adds this module's node names to `into`.
    ///
    /// Called once per inflater. The catalog does not know what it is registering
    /// against — an application may build several inflaters with different
    /// [Wiring], and a document reloaded at runtime gets a fresh one.
    void register(Inflatable.Catalog into);
}
