/*
 * The layout probe for goldberry-media.
 *
 * Prints, as a Java properties file, the size and alignment of every FFmpeg
 * struct the Engine touches and the offset and size of every field the Java
 * side reads, plus the library majors and the handful of constants the Java side
 * hard-codes. The media superbuild compiles and runs it once per platform and
 * packages the output beside the libraries; `FfmpegLayouts` in Java is checked
 * against it by a unit test and again, once, before the Engine touches a struct.
 *
 * It is compiled against the headers of the FFmpeg it describes and links
 * nothing: every value is a compile-time constant. That is also why it can run
 * on a machine that has headers and no libraries.
 *
 * Usage: ffmpeg_layout [output-file]. With no argument it writes to stdout; the
 * superbuild passes a path, so no shell redirection has to survive CMake's
 * quoting on four generators.
 *
 * Keys:
 *   struct.<Name>.sizeof / struct.<Name>.alignof
 *   field.<Name>.<field>.offset / field.<Name>.<field>.sizeof
 *   const.<NAME>
 *   version.<library>.major
 */
#include <stddef.h>
#include <stdio.h>
#include <errno.h>

#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavformat/avio.h>
#include <libavutil/avutil.h>
#include <libavutil/channel_layout.h>
#include <libavutil/hwcontext.h>
#include <libavutil/pixfmt.h>
#include <libavutil/samplefmt.h>
#include <libswresample/version_major.h>
#include <libswscale/swscale.h>
#include <libswscale/version_major.h>

#define STRUCT(T) \
    printf("struct.%s.sizeof=%zu\nstruct.%s.alignof=%zu\n", #T, sizeof(T), #T, _Alignof(T))
#define FIELD(T, f) \
    printf("field.%s.%s.offset=%zu\nfield.%s.%s.sizeof=%zu\n", #T, #f, offsetof(T, f), #T, #f, sizeof(((T *)0)->f))
#define CONST(name, value) printf("const.%s=%lld\n", name, (long long)(value))

int main(int argc, char **argv) {
    if (argc > 1 && freopen(argv[1], "w", stdout) == NULL) {
        perror(argv[1]);
        return 1;
    }
    printf("# FFmpeg layout for goldberry-media, generated by ffmpeg_layout.c\n");
    printf("version.avformat.major=%d\n", LIBAVFORMAT_VERSION_MAJOR);
    printf("version.avcodec.major=%d\n", LIBAVCODEC_VERSION_MAJOR);
    printf("version.avutil.major=%d\n", LIBAVUTIL_VERSION_MAJOR);
    printf("version.swresample.major=%d\n", LIBSWRESAMPLE_VERSION_MAJOR);
    printf("version.swscale.major=%d\n", LIBSWSCALE_VERSION_MAJOR);

    STRUCT(AVRational);
    FIELD(AVRational, num);
    FIELD(AVRational, den);

    STRUCT(AVChannelLayout);
    FIELD(AVChannelLayout, order);
    FIELD(AVChannelLayout, nb_channels);
    FIELD(AVChannelLayout, u.mask);

    STRUCT(AVFormatContext);
    FIELD(AVFormatContext, nb_streams);
    FIELD(AVFormatContext, streams);
    FIELD(AVFormatContext, pb);
    FIELD(AVFormatContext, duration);
    FIELD(AVFormatContext, flags);

    /* avio_alloc_context's contract: the buffer handed to it may have been
     * replaced by the time the context is freed, so the one to free is the
     * context's own field and not the pointer that was passed in. */
    STRUCT(AVIOContext);
    FIELD(AVIOContext, buffer);

    /* Read to list what this build decodes and demuxes (MediaCapabilities):
     * av_codec_iterate and av_demuxer_iterate hand back these, and the public
     * fields at their head are the only way to ask which one it is. */
    STRUCT(AVCodec);
    FIELD(AVCodec, name);
    FIELD(AVCodec, type);
    FIELD(AVCodec, id);

    STRUCT(AVInputFormat);
    FIELD(AVInputFormat, name);

    STRUCT(AVStream);
    FIELD(AVStream, index);
    FIELD(AVStream, codecpar);
    FIELD(AVStream, time_base);
    FIELD(AVStream, duration);
    FIELD(AVStream, nb_frames);
    FIELD(AVStream, disposition);
    FIELD(AVStream, discard);
    FIELD(AVStream, metadata);
    FIELD(AVStream, avg_frame_rate);
    FIELD(AVStream, attached_pic);
    FIELD(AVStream, r_frame_rate);

    /* A track's language and title are entries of its metadata dictionary
     * (av_dict_get), read to label a track menu. */
    STRUCT(AVDictionaryEntry);
    FIELD(AVDictionaryEntry, key);
    FIELD(AVDictionaryEntry, value);

    STRUCT(AVCodecParameters);
    FIELD(AVCodecParameters, codec_type);
    FIELD(AVCodecParameters, codec_id);
    FIELD(AVCodecParameters, extradata);
    FIELD(AVCodecParameters, extradata_size);
    FIELD(AVCodecParameters, format);
    FIELD(AVCodecParameters, bit_rate);
    FIELD(AVCodecParameters, profile);
    FIELD(AVCodecParameters, level);
    FIELD(AVCodecParameters, width);
    FIELD(AVCodecParameters, height);
    FIELD(AVCodecParameters, framerate);
    FIELD(AVCodecParameters, color_range);
    FIELD(AVCodecParameters, color_primaries);
    FIELD(AVCodecParameters, color_trc);
    FIELD(AVCodecParameters, color_space);
    FIELD(AVCodecParameters, chroma_location);
    FIELD(AVCodecParameters, ch_layout);
    FIELD(AVCodecParameters, sample_rate);

    STRUCT(AVCodecContext);
    FIELD(AVCodecContext, codec_id);
    FIELD(AVCodecContext, opaque);
    FIELD(AVCodecContext, flags);
    FIELD(AVCodecContext, pix_fmt);
    FIELD(AVCodecContext, get_format);
    FIELD(AVCodecContext, sample_fmt);
    FIELD(AVCodecContext, thread_count);
    FIELD(AVCodecContext, pkt_timebase);
    FIELD(AVCodecContext, hw_device_ctx);

    /* Hardware decode: avcodec_get_hw_config hands these
     * back, one per way a decoder can use a device, and there is no accessor. */
    STRUCT(AVCodecHWConfig);
    FIELD(AVCodecHWConfig, pix_fmt);
    FIELD(AVCodecHWConfig, methods);
    FIELD(AVCodecHWConfig, device_type);

    STRUCT(AVPacket);
    FIELD(AVPacket, pts);
    FIELD(AVPacket, dts);
    FIELD(AVPacket, data);
    FIELD(AVPacket, size);
    FIELD(AVPacket, stream_index);
    FIELD(AVPacket, flags);
    FIELD(AVPacket, duration);

    STRUCT(AVFrame);
    FIELD(AVFrame, data);
    FIELD(AVFrame, linesize);
    FIELD(AVFrame, width);
    FIELD(AVFrame, height);
    FIELD(AVFrame, nb_samples);
    FIELD(AVFrame, format);
    FIELD(AVFrame, pts);
    FIELD(AVFrame, pkt_dts);
    FIELD(AVFrame, sample_rate);
    FIELD(AVFrame, hw_frames_ctx);
    FIELD(AVFrame, flags);
    FIELD(AVFrame, color_range);
    FIELD(AVFrame, color_primaries);
    FIELD(AVFrame, color_trc);
    FIELD(AVFrame, colorspace);
    FIELD(AVFrame, chroma_location);
    FIELD(AVFrame, duration);
    FIELD(AVFrame, ch_layout);

    /* Constants the Java side reads rather than writes down. EAGAIN is the one that differs by
     * platform (35 on macOS, 11 on Linux and Windows), which is exactly why it
     * is read from here rather than assumed. */
    CONST("AVERROR_EOF", AVERROR_EOF);
    CONST("AVERROR_EXIT", AVERROR_EXIT);
    CONST("AVERROR_EAGAIN", AVERROR(EAGAIN));
    CONST("AVERROR_EIO", AVERROR(EIO));
    CONST("AVERROR_DECODER_NOT_FOUND", AVERROR_DECODER_NOT_FOUND);
    CONST("AVERROR_INVALIDDATA", AVERROR_INVALIDDATA);
    CONST("AVSEEK_SIZE", AVSEEK_SIZE);
    CONST("AVSEEK_FORCE", AVSEEK_FORCE);
    CONST("AV_PROFILE_UNKNOWN", AV_PROFILE_UNKNOWN);
    CONST("AV_LEVEL_UNKNOWN", AV_LEVEL_UNKNOWN);
    CONST("AV_NOPTS_VALUE", AV_NOPTS_VALUE);
    CONST("AV_TIME_BASE", AV_TIME_BASE);
    CONST("AVMEDIA_TYPE_VIDEO", AVMEDIA_TYPE_VIDEO);
    CONST("AVMEDIA_TYPE_AUDIO", AVMEDIA_TYPE_AUDIO);
    CONST("AVMEDIA_TYPE_SUBTITLE", AVMEDIA_TYPE_SUBTITLE);
    CONST("AVMEDIA_TYPE_ATTACHMENT", AVMEDIA_TYPE_ATTACHMENT);
    CONST("AV_DISPOSITION_DEFAULT", AV_DISPOSITION_DEFAULT);
    CONST("AV_DISPOSITION_ATTACHED_PIC", AV_DISPOSITION_ATTACHED_PIC);
    CONST("AV_DISPOSITION_FORCED", AV_DISPOSITION_FORCED);
    CONST("AVDISCARD_DEFAULT", AVDISCARD_DEFAULT);
    CONST("AVDISCARD_ALL", AVDISCARD_ALL);
    CONST("AV_PIX_FMT_NONE", AV_PIX_FMT_NONE);
    CONST("AV_PIX_FMT_YUV420P", AV_PIX_FMT_YUV420P);
    CONST("AV_PIX_FMT_NV12", AV_PIX_FMT_NV12);
    CONST("AV_PIX_FMT_P010LE", AV_PIX_FMT_P010LE);
    CONST("AV_PIX_FMT_BGRA", AV_PIX_FMT_BGRA);
    CONST("AV_PIX_FMT_YUV420P10LE", AV_PIX_FMT_YUV420P10LE);
    /* A picture with an alpha plane: VP9 colour and its alpha stream, put together. */
    CONST("AV_PIX_FMT_YUVA420P", AV_PIX_FMT_YUVA420P);
    /* What CPU present converts with (phase 3): the colour a decoder tagged a
     * frame with, and the swscale flags and coefficient tables that honour it. */
    CONST("AVCOL_SPC_BT709", AVCOL_SPC_BT709);
    CONST("AVCOL_SPC_UNSPECIFIED", AVCOL_SPC_UNSPECIFIED);
    CONST("AVCOL_SPC_BT470BG", AVCOL_SPC_BT470BG);
    CONST("AVCOL_SPC_SMPTE170M", AVCOL_SPC_SMPTE170M);
    CONST("AVCOL_SPC_BT2020_NCL", AVCOL_SPC_BT2020_NCL);
    CONST("AVCOL_SPC_BT2020_CL", AVCOL_SPC_BT2020_CL);
    CONST("AVCOL_RANGE_JPEG", AVCOL_RANGE_JPEG);
    CONST("SWS_BILINEAR", SWS_BILINEAR);
    CONST("SWS_ACCURATE_RND", SWS_ACCURATE_RND);
    CONST("SWS_BITEXACT", SWS_BITEXACT);
    CONST("SWS_FULL_CHR_H_INT", SWS_FULL_CHR_H_INT);
    CONST("SWS_CS_ITU601", SWS_CS_ITU601);
    CONST("SWS_CS_ITU709", SWS_CS_ITU709);
    CONST("SWS_CS_BT2020", SWS_CS_BT2020);
    CONST("AV_SAMPLE_FMT_NONE", AV_SAMPLE_FMT_NONE);
    CONST("AV_SAMPLE_FMT_U8", AV_SAMPLE_FMT_U8);
    CONST("AV_SAMPLE_FMT_S16", AV_SAMPLE_FMT_S16);
    CONST("AV_SAMPLE_FMT_S32", AV_SAMPLE_FMT_S32);
    CONST("AV_SAMPLE_FMT_DBL", AV_SAMPLE_FMT_DBL);
    CONST("AV_SAMPLE_FMT_U8P", AV_SAMPLE_FMT_U8P);
    CONST("AV_SAMPLE_FMT_S16P", AV_SAMPLE_FMT_S16P);
    CONST("AV_SAMPLE_FMT_S32P", AV_SAMPLE_FMT_S32P);
    CONST("AV_SAMPLE_FMT_DBLP", AV_SAMPLE_FMT_DBLP);
    CONST("AV_SAMPLE_FMT_S64", AV_SAMPLE_FMT_S64);
    CONST("AV_SAMPLE_FMT_S64P", AV_SAMPLE_FMT_S64P);
    CONST("AV_SAMPLE_FMT_FLT", AV_SAMPLE_FMT_FLT);
    CONST("AV_SAMPLE_FMT_FLTP", AV_SAMPLE_FMT_FLTP);
    CONST("AV_LOG_QUIET", AV_LOG_QUIET);
    CONST("AV_LOG_ERROR", AV_LOG_ERROR);
    CONST("AV_LOG_WARNING", AV_LOG_WARNING);
    CONST("AV_CHANNEL_ORDER_NATIVE", AV_CHANNEL_ORDER_NATIVE);
    CONST("AVFMT_FLAG_CUSTOM_IO", AVFMT_FLAG_CUSTOM_IO);
    CONST("AV_PKT_FLAG_KEY", AV_PKT_FLAG_KEY);
    /* A Matroska BlockAdditional, which av_packet_get_side_data hands back: an
     * 8-byte big-endian BlockAddID, then the bytes. ID 1 is a WebM track's alpha. */
    CONST("AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL", AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL);
    CONST("AVSEEK_FLAG_BACKWARD", AVSEEK_FLAG_BACKWARD);
    CONST("AVSEEK_FLAG_ANY", AVSEEK_FLAG_ANY);
    CONST("AVMEDIA_TYPE_DATA", AVMEDIA_TYPE_DATA);
    CONST("AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX", AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX);
    CONST("AV_HWDEVICE_TYPE_NONE", AV_HWDEVICE_TYPE_NONE);
    return 0;
}
