package io.github.digitalsmile.goldberry;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Properties;

/// Entry point and version information for the Goldberry toolkit.
///
/// The launch API described in `docs/ARCHITECTURE.md` §4 -- `Goldberry.launch(app)`,
/// which takes over the *calling* thread as the UI thread rather than spawning
/// one, because AppKit requires the process' first thread -- arrives with the
/// backend skeleton in M0.
public final class Goldberry {

    private static final String BUILD_INFO_RESOURCE = "build-info.properties";

    private static final String VERSION = loadVersion();

    private Goldberry() {
    }

    /// The toolkit version, as generated by the build and published to Maven Central.
    public static String version() {
        return VERSION;
    }

    private static String loadVersion() {
        try (InputStream in = Goldberry.class.getResourceAsStream(BUILD_INFO_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        BUILD_INFO_RESOURCE + " is missing from the goldberry-core artifact");
            }
            var properties = new Properties();
            properties.load(in);
            var version = properties.getProperty("version");
            if (version == null || version.isBlank()) {
                throw new IllegalStateException(
                        BUILD_INFO_RESOURCE + " does not declare a version");
            }
            return version;
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to read " + BUILD_INFO_RESOURCE, e);
        }
    }
}
