package io.github.digitalsmile.goldberry;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Properties;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.function.Supplier;

/// Running the toolkit: the loop, background work, and the version.
///
/// Paired with [Window]. Between them an application needs no other Goldberry
/// type to put something on screen:
///
/// ```java
/// public static void main(String[] args) {
///     var window = Window.open("Hello", 960, 640);
///     window.onPaint(frame -> frame.fill(0xFF2E3440));
///     Goldberry.run();
/// }
/// ```
///
/// [#run()] takes over the **calling** thread as the UI thread rather than
/// spawning one, because AppKit requires the process's first thread and a rule
/// that holds on only two platforms is not a rule (`docs/ARCHITECTURE.md` §4).
public final class Goldberry {

    private static final String BUILD_INFO_RESOURCE = "build-info.properties";

    private static final String VERSION = loadVersion();

    private Goldberry() {
    }

    /// The toolkit version, as generated by the build and published to Maven Central.
    public static String version() {
        return VERSION;
    }

    /// Runs until every window has closed.
    ///
    /// The calling thread becomes the UI thread and stays here. It is idle
    /// whenever nothing is happening — an application that draws nothing costs
    /// nothing.
    ///
    /// @throws io.github.digitalsmile.goldberry.backend.BackendException if no
    ///         window has been opened, or if called off the UI thread
    public static void run() {
        if (!GoldberryRuntime.isStarted()) {
            throw GoldberryRuntime.notStarted();
        }
        GoldberryRuntime.get().run();
    }

    /// Asks the loop to finish. Safe from any thread.
    public static void stop() {
        if (GoldberryRuntime.isStarted()) {
            GoldberryRuntime.get().loop().stop();
        }
    }

    /// Runs `work` off the UI thread and delivers its result **on** the UI
    /// thread.
    ///
    /// Every callback chained onto the returned future is therefore already
    /// somewhere it may touch a window — no hand-off to write, and no rule to
    /// remember about which thread a callback runs on (ADR-0020):
    ///
    /// ```java
    /// Goldberry.async(() -> readTheFile())
    ///          .thenAccept(text -> window.title(text));
    /// ```
    public static <T> CompletableFuture<T> async(Supplier<T> work) {
        return GoldberryRuntime.get().loop().supplyAsync(work);
    }

    /// Runs `work` off the UI thread with nothing to return.
    public static CompletableFuture<Void> async(Runnable work) {
        return GoldberryRuntime.get().loop().runAsync(work);
    }

    /// Queues `task` to run on the UI thread. Safe from any thread.
    ///
    /// The escape hatch for code that is not shaped like a future — a callback
    /// from a library, say. [#async] is the usual answer.
    public static Executor ui() {
        return GoldberryRuntime.get().loop().ui();
    }

    /// Whether the caller is on the UI thread.
    public static boolean isUiThread() {
        return GoldberryRuntime.isStarted() && GoldberryRuntime.get().loop().ui().isUiThread();
    }

    /// Opens a window for `application`, runs it, and takes it down again.
    ///
    /// The front door, and for most applications the only line of `main`:
    ///
    /// ```java
    /// public static void main(String[] args) {
    ///     Goldberry.launch(new MyApp(), args);
    /// }
    /// ```
    ///
    /// Everything between opening the window and closing the last font is the
    /// launcher's — the element tree, the render tree, the renderer, the router,
    /// the frame loop, damage, the hit-test snapshot and the shutdown ordering —
    /// because none of it is a decision an application makes differently
    /// ([ADR-0093](../../../../../book/src/adr/0093-an-application-is-a-root-widget.md)).
    ///
    /// Returns when the loop ends: the last window closed, or something called
    /// [#stop()].
    ///
    /// @param args the process arguments, from which the launcher reads
    ///             `--frames=N` and `--size=WxH` and ignores everything else
    public static void launch(Application application, String[] args) {
        new Launcher(application, Launcher.Options.of(args)).run();
    }

    /// The same, for an application with no arguments to give.
    public static void launch(Application application) {
        new Launcher(application, Launcher.Options.NONE).run();
    }

    /// Closes every window and releases the backend.
    ///
    /// Rarely needed: [#run()] returns once the last window closes, and the
    /// process usually exits after that. It exists for applications that outlive
    /// their windows.
    public static void shutdown() {
        GoldberryRuntime.shutdown();
    }

    private static String loadVersion() {
        try (InputStream in = Goldberry.class.getResourceAsStream(BUILD_INFO_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        BUILD_INFO_RESOURCE + " is missing from the goldberry-core artifact");
            }
            var properties = new Properties();
            properties.load(in);
            var version = properties.getProperty("version");
            if (version == null || version.isBlank()) {
                throw new IllegalStateException(
                        BUILD_INFO_RESOURCE + " does not declare a version");
            }
            return version;
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to read " + BUILD_INFO_RESOURCE, e);
        }
    }
}
